[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
ffi = true # would be good to keep it to false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
